spring:
  application:
    name: MembershipManagementSystem

  datasource:
    url: jdbc:mysql://localhost:3306/membership_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.mailtrap.io
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/google #${GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: email

server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        max-age: 30m
  admin:
    email: admin@gmail.com
    password: Voice36!

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Account lockout configuration
account:
  lockout:
    max-attempts: 5 # Maximum failed login attempts before lockout
    duration-minutes: 30 # Lockout duration in minutes

paypal:
  mode: sandbox
  client-id:
  client-secret:
  webhook-id:
  currency: CAD
